### ISSUE TITLE
replication status monitoring 플러그인 작성

### ISSUE THREAD

**Issue by namenu** [genesos/munin-plugins#1]
https://github.com/ridibooks/devops-toolbox/blob/master/mysql/monitor.replication.sh

현재는 위 스크립트를 crontab에 수동으로 등록해서 사용해야함.
Munin 을 통한 일관성있는 모니터링 및 알람 시스템을 사용할 수 있도록 munin plugins 으로 작성

**Comment by genesos** [comment]
생각해보았는데, munin 플러그인은 용이성 때문에라도 해야하는데,
저 스크립트도 1분만에 체크가능한점에서 병행해서 사용하는게 좋지 않을까 싶네요.(munin는 5분이니...)
